### PR TITLE
migration to polymer 2

### PR DESCRIPTION
**Pull request by jefBinomed**
It's a proposition of evolution to be ready to polymer 2 ;)

### CODE REVIEW

**Comment by LostInBrittany** [comment]
Wow, thanks for the PR Jef!

I hesitate to put the preview 2.0 in the master, I had thought about a  `2.0-preview` branch like they do in most Polymer elements. 

There are only some details missing, like using `slot` instead of `content`, or the `variants` in the `bower.json`
as in https://github.com/PolymerElements/iron-ajax/blob/2.0-preview/bower.json

 But I really like it!

**Comment by jefBinomed** [comment]
I think the main idea is not to put it in master but to propose for the moment a 2.0-preview branch :) 

But I didn't understand really how to make it work for your demos.

**Comment by jefBinomed** [comment]
I update the branch with migration to polymer 2 rc

**Comment by jensnilsson** [comment]
Great work, will this be merged anytime soon?

**Comment by LostInBrittany** [comment]
As most of official polymer components, for the moment the main branch will
be an hybrid 1.x-2.0 compatible with both versions of Polymer. Making this
one the main branch would forbid 1.x users from using it.
I am merging it in a 2.x branch soon, maybe today if I have time.

**Comment by alimd** [comment]
@jefBinomed @LostInBrittany Please keep this project compatible with polymer 1 and keep it in hybrid mode
And please use Polymer#1-2 in your bower 
I think there is no benefit for use polymer 2 separate branch because make double time for support both versions

**Pull request closed without merging**
